# Generated by Django 5.2.5 on 2025-09-21 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='candidate', max_length=10)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('resume', models.URLField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10, null=True)),
                ('hr', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hired', 'Hired'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='active', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(limit_choices_to={'profile__role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('assessment_Pending', 'Assessment Pending'), ('rejected', 'Rejected'), ('Assesment_Completed', 'Assesment Completed')], default='scheduled', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'profile__role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL)),
                ('hr', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interviews', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='smartInterviewApp.vacancies')),
            ],
        ),
    ]
