# Generated by Django 5.2.5 on 2025-08-23 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0002_interview_hr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='hr',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='recruiter',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('assessment_Pending', 'Assessment Pending'), ('rejected', 'Rejected'), ('Assesment_Completed', 'Assesment Completed')], default='scheduled', max_length=20),
        ),
    ]
