# Generated by Django 5.2.5 on 2025-09-05 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0004_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
