# Generated by Django 5.2.5 on 2025-09-06 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0005_alter_interview_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='hr',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hr',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
