# Generated by Django 5.2.5 on 2025-09-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0006_remove_interview_hr_userprofile_hr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hr',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
