# Generated by Django 5.2.5 on 2025-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0007_interview_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
