from __future__ import annotations


SKILL_TAXONOMY: dict[str, dict[str, object]] = {
    'Python': {
        'aliases': ['python', 'python 3', 'python 3.x', 'python3', 'python 2.7'],
        'domain': 'engineering',
        'family': 'engineering/software',
        'related': {'Django': 0.94, 'Flask': 0.92, 'FastAPI': 0.92, 'DRF': 0.9, 'Pandas': 0.72, 'NumPy': 0.68, 'Celery': 0.74},
    },
    'Django': {'aliases': ['django', 'django framework'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Python': 0.96, 'DRF': 0.9, 'Celery': 0.72, 'REST API': 0.78}},
    'Flask': {'aliases': ['flask'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Python': 0.94, 'REST API': 0.76}},
    'FastAPI': {'aliases': ['fastapi', 'fast api'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Python': 0.94, 'REST API': 0.82}},
    'DRF': {'aliases': ['drf', 'django rest framework'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Django': 0.92, 'Python': 0.84, 'REST API': 0.82}},
    'Celery': {'aliases': ['celery'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Python': 0.76, 'Redis': 0.72, 'Microservices': 0.62}},
    'Pandas': {'aliases': ['pandas'], 'domain': 'data_ai_ml', 'family': 'data/analytics', 'related': {'Python': 0.7, 'Data Analysis': 0.78, 'Data Science': 0.72, 'NumPy': 0.82}},
    'NumPy': {'aliases': ['numpy'], 'domain': 'data_ai_ml', 'family': 'data/analytics', 'related': {'Python': 0.66, 'Pandas': 0.82, 'Machine Learning': 0.58}},
    'Java': {'aliases': ['java'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Spring Boot': 0.94, 'Hibernate': 0.86, 'OOP': 0.72}},
    'Spring Boot': {'aliases': ['spring boot', 'springboot'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Java': 0.96, 'Hibernate': 0.8, 'Microservices': 0.72, 'REST API': 0.78}},
    'Hibernate': {'aliases': ['hibernate'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Java': 0.86, 'Spring Boot': 0.8}},
    'JavaScript': {'aliases': ['javascript', 'java script', 'js'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'TypeScript': 0.9, 'React': 0.82, 'Angular': 0.8, 'Vue': 0.8, 'Node.js': 0.84}},
    'TypeScript': {'aliases': ['typescript', 'ts'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'JavaScript': 0.92, 'React': 0.78, 'Angular': 0.8, 'Node.js': 0.76}},
    'Node.js': {'aliases': ['node.js', 'nodejs', 'node js'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'JavaScript': 0.88, 'TypeScript': 0.8, 'Express': 0.92, 'REST API': 0.74}},
    'Express': {'aliases': ['express', 'express.js', 'expressjs'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Node.js': 0.94, 'JavaScript': 0.78, 'REST API': 0.72}},
    'React': {'aliases': ['react', 'reactjs', 'react.js'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'JavaScript': 0.84, 'TypeScript': 0.78, 'HTML': 0.72, 'CSS': 0.7}},
    'Angular': {'aliases': ['angular', 'angularjs'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'JavaScript': 0.82, 'TypeScript': 0.84, 'HTML': 0.72, 'CSS': 0.7}},
    'Vue': {'aliases': ['vue', 'vue.js', 'vuejs'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'JavaScript': 0.82, 'HTML': 0.7, 'CSS': 0.7}},
    'HTML': {'aliases': ['html', 'html5'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'CSS': 0.88, 'React': 0.6, 'Angular': 0.6, 'Vue': 0.6}},
    'CSS': {'aliases': ['css', 'css3'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'HTML': 0.88, 'Bootstrap': 0.82, 'Tailwind': 0.82}},
    'Bootstrap': {'aliases': ['bootstrap'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'CSS': 0.86, 'HTML': 0.74}},
    'Tailwind': {'aliases': ['tailwind', 'tailwind css', 'tailwindcss'], 'domain': 'engineering', 'family': 'engineering/frontend', 'related': {'CSS': 0.88, 'HTML': 0.68}},
    'MySQL': {'aliases': ['mysql'], 'domain': 'engineering', 'family': 'engineering/data', 'related': {'SQL': 0.9, 'PostgreSQL': 0.72}},
    'PostgreSQL': {'aliases': ['postgresql', 'postgres', 'postgre'], 'domain': 'engineering', 'family': 'engineering/data', 'related': {'SQL': 0.92, 'MySQL': 0.72}},
    'MongoDB': {'aliases': ['mongodb', 'mongo db', 'mongo'], 'domain': 'engineering', 'family': 'engineering/data', 'related': {'NoSQL': 0.88, 'Redis': 0.52}},
    'Redis': {'aliases': ['redis'], 'domain': 'engineering', 'family': 'engineering/data', 'related': {'Celery': 0.72, 'MongoDB': 0.4}},
    'SQL': {'aliases': ['sql'], 'domain': 'data_ai_ml', 'family': 'data/analytics', 'related': {'PostgreSQL': 0.88, 'MySQL': 0.84, 'ETL': 0.62, 'Data Analysis': 0.66}},
    'NoSQL': {'aliases': ['nosql', 'no sql'], 'domain': 'engineering', 'family': 'engineering/data', 'related': {'MongoDB': 0.88}},
    'REST API': {'aliases': ['rest api', 'restful api', 'rest services', 'api development', 'apis'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'GraphQL': 0.56, 'Django': 0.72, 'Flask': 0.72, 'FastAPI': 0.8, 'DRF': 0.84, 'Express': 0.72}},
    'GraphQL': {'aliases': ['graphql', 'graph ql'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'REST API': 0.56}},
    'Git': {'aliases': ['git', 'version control'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'CI/CD': 0.72, 'GitHub Actions': 0.76, 'GitLab CI': 0.74}},
    'CI/CD': {'aliases': ['ci/cd', 'cicd', 'continuous integration', 'continuous deployment'], 'domain': 'devops_cloud', 'family': 'devops/automation', 'related': {'Git': 0.72, 'Jenkins': 0.86, 'GitHub Actions': 0.88, 'GitLab CI': 0.88}},
    'Jenkins': {'aliases': ['jenkins'], 'domain': 'devops_cloud', 'family': 'devops/automation', 'related': {'CI/CD': 0.9}},
    'Microservices': {'aliases': ['microservices', 'micro services'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'REST API': 0.68, 'Docker': 0.62, 'Kubernetes': 0.66}},
    'OOP': {'aliases': ['oop', 'object oriented programming', 'object-oriented programming'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Java': 0.72, 'Python': 0.54, 'SDLC': 0.48}},
    'SDLC': {'aliases': ['sdlc', 'software development lifecycle'], 'domain': 'engineering', 'family': 'engineering/software', 'related': {'Agile': 0.56, 'Scrum': 0.52}},
    'AWS': {'aliases': ['aws', 'amazon web services'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'Docker': 0.66, 'Kubernetes': 0.62, 'Terraform': 0.74, 'Linux': 0.56}},
    'Azure': {'aliases': ['azure', 'microsoft azure'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'Terraform': 0.68, 'Linux': 0.48}},
    'GCP': {'aliases': ['gcp', 'google cloud', 'google cloud platform'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'Terraform': 0.66, 'Linux': 0.48}},
    'Docker': {'aliases': ['docker', 'containerization'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'Kubernetes': 0.88, 'AWS': 0.66, 'Linux': 0.66, 'Microservices': 0.64}},
    'Kubernetes': {'aliases': ['kubernetes', 'k8s'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'Docker': 0.9, 'Terraform': 0.66, 'AWS': 0.62}},
    'Terraform': {'aliases': ['terraform'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'AWS': 0.78, 'Azure': 0.72, 'GCP': 0.7, 'Ansible': 0.72}},
    'Ansible': {'aliases': ['ansible'], 'domain': 'devops_cloud', 'family': 'devops/cloud', 'related': {'Terraform': 0.72, 'Linux': 0.58}},
    'Linux': {'aliases': ['linux'], 'domain': 'devops_cloud', 'family': 'devops/platform', 'related': {'Nginx': 0.68, 'Docker': 0.64, 'AWS': 0.54}},
    'Nginx': {'aliases': ['nginx'], 'domain': 'devops_cloud', 'family': 'devops/platform', 'related': {'Linux': 0.68}},
    'Monitoring': {'aliases': ['monitoring', 'observability'], 'domain': 'devops_cloud', 'family': 'devops/platform', 'related': {'Prometheus': 0.88, 'Grafana': 0.88}},
    'Prometheus': {'aliases': ['prometheus'], 'domain': 'devops_cloud', 'family': 'devops/platform', 'related': {'Monitoring': 0.9, 'Grafana': 0.84}},
    'Grafana': {'aliases': ['grafana'], 'domain': 'devops_cloud', 'family': 'devops/platform', 'related': {'Monitoring': 0.9, 'Prometheus': 0.84}},
    'GitHub Actions': {'aliases': ['github actions'], 'domain': 'devops_cloud', 'family': 'devops/automation', 'related': {'CI/CD': 0.9, 'Git': 0.76}},
    'GitLab CI': {'aliases': ['gitlab ci', 'gitlab pipeline', 'gitlab pipelines'], 'domain': 'devops_cloud', 'family': 'devops/automation', 'related': {'CI/CD': 0.9, 'Git': 0.72}},
    'Machine Learning': {'aliases': ['machine learning', 'ml'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'Deep Learning': 0.82, 'Data Science': 0.82, 'TensorFlow': 0.74, 'PyTorch': 0.74, 'Python': 0.64}},
    'Deep Learning': {'aliases': ['deep learning'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'Machine Learning': 0.86, 'TensorFlow': 0.84, 'PyTorch': 0.84}},
    'TensorFlow': {'aliases': ['tensorflow', 'tensor flow'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'Deep Learning': 0.86, 'Machine Learning': 0.72, 'Python': 0.58}},
    'PyTorch': {'aliases': ['pytorch', 'py torch'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'Deep Learning': 0.86, 'Machine Learning': 0.72, 'Python': 0.58}},
    'NLP': {'aliases': ['nlp', 'natural language processing'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'LLM': 0.86, 'Prompt Engineering': 0.74, 'Machine Learning': 0.68}},
    'LLM': {'aliases': ['llm', 'large language model', 'large language models'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'NLP': 0.9, 'Prompt Engineering': 0.82}},
    'Prompt Engineering': {'aliases': ['prompt engineering', 'prompt design'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'LLM': 0.84, 'NLP': 0.72}},
    'Data Analysis': {'aliases': ['data analysis', 'analytical reporting'], 'domain': 'analytics_bi', 'family': 'analytics/business_intelligence', 'related': {'SQL': 0.68, 'Excel': 0.74, 'Power BI': 0.74, 'Tableau': 0.74, 'Pandas': 0.72}},
    'Data Science': {'aliases': ['data science', 'data scientist'], 'domain': 'data_ai_ml', 'family': 'data/ml', 'related': {'Machine Learning': 0.84, 'Data Analysis': 0.76, 'Python': 0.66}},
    'ETL': {'aliases': ['etl', 'extract transform load'], 'domain': 'data_ai_ml', 'family': 'data/engineering', 'related': {'Data Pipelines': 0.88, 'SQL': 0.66, 'Airflow': 0.76, 'Spark': 0.74}},
    'Data Pipelines': {'aliases': ['data pipelines', 'data pipeline'], 'domain': 'data_ai_ml', 'family': 'data/engineering', 'related': {'ETL': 0.9, 'Airflow': 0.82, 'Spark': 0.78}},
    'Spark': {'aliases': ['spark', 'apache spark'], 'domain': 'data_ai_ml', 'family': 'data/engineering', 'related': {'ETL': 0.74, 'Data Pipelines': 0.8}},
    'Airflow': {'aliases': ['airflow', 'apache airflow'], 'domain': 'data_ai_ml', 'family': 'data/engineering', 'related': {'ETL': 0.8, 'Data Pipelines': 0.82}},
    'Power BI': {'aliases': ['power bi', 'powerbi'], 'domain': 'analytics_bi', 'family': 'analytics/business_intelligence', 'related': {'Tableau': 0.8, 'Data Analysis': 0.76, 'Excel': 0.74}},
    'Tableau': {'aliases': ['tableau'], 'domain': 'analytics_bi', 'family': 'analytics/business_intelligence', 'related': {'Power BI': 0.8, 'Data Analysis': 0.76, 'Excel': 0.72}},
    'Manual Testing': {'aliases': ['manual testing'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'QA': 0.88, 'Regression Testing': 0.78, 'UAT': 0.72}},
    'Automation Testing': {'aliases': ['automation testing', 'test automation'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Selenium': 0.84, 'Cypress': 0.8, 'Playwright': 0.8, 'API Testing': 0.7}},
    'Selenium': {'aliases': ['selenium'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Automation Testing': 0.86, 'Regression Testing': 0.66}},
    'Cypress': {'aliases': ['cypress'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Automation Testing': 0.82, 'Playwright': 0.72}},
    'Playwright': {'aliases': ['playwright'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Automation Testing': 0.82, 'Cypress': 0.72}},
    'API Testing': {'aliases': ['api testing'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Postman': 0.84, 'Automation Testing': 0.72, 'REST API': 0.68}},
    'Postman': {'aliases': ['postman'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'API Testing': 0.86}},
    'JMeter': {'aliases': ['jmeter', 'apache jmeter'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Load Testing': 0.92}},
    'Load Testing': {'aliases': ['load testing', 'performance testing'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'JMeter': 0.92}},
    'Regression Testing': {'aliases': ['regression testing', 'regression'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Manual Testing': 0.78, 'Automation Testing': 0.68}},
    'UAT': {'aliases': ['uat', 'user acceptance testing'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Manual Testing': 0.72, 'QA': 0.68}},
    'QA': {'aliases': ['qa', 'quality assurance'], 'domain': 'qa_testing', 'family': 'qa/testing', 'related': {'Manual Testing': 0.88, 'Automation Testing': 0.72}},
    'Lead Generation': {'aliases': ['lead generation', 'lead gen'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Prospecting': 0.88, 'Cold Calling': 0.78, 'Cold Email': 0.78, 'Pipeline Management': 0.64}},
    'Prospecting': {'aliases': ['prospecting'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Lead Generation': 0.9, 'Cold Calling': 0.76, 'Cold Email': 0.76}},
    'Cold Calling': {'aliases': ['cold calling'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Lead Generation': 0.78, 'Prospecting': 0.76, 'Inside Sales': 0.68}},
    'Cold Email': {'aliases': ['cold email', 'cold emailing'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Lead Generation': 0.78, 'Prospecting': 0.76}},
    'CRM': {'aliases': ['crm', 'customer relationship management'], 'domain': 'sales_bd', 'family': 'sales/customer_management', 'related': {'Salesforce': 0.88, 'HubSpot': 0.86, 'Zoho CRM': 0.84, 'Client Relationship Management': 0.9, 'Customer Success': 0.62}},
    'Salesforce': {'aliases': ['salesforce'], 'domain': 'sales_bd', 'family': 'sales/customer_management', 'related': {'CRM': 0.9, 'Apex': 0.86, 'Lightning': 0.86, 'SOQL': 0.78, 'Visualforce': 0.74}},
    'HubSpot': {'aliases': ['hubspot', 'hub spot'], 'domain': 'sales_bd', 'family': 'sales/customer_management', 'related': {'CRM': 0.88, 'Marketing Automation': 0.72}},
    'Zoho CRM': {'aliases': ['zoho crm', 'zoho'], 'domain': 'sales_bd', 'family': 'sales/customer_management', 'related': {'CRM': 0.86}},
    'B2B Sales': {'aliases': ['b2b sales'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Enterprise Sales': 0.82, 'SaaS Sales': 0.78, 'Account Management': 0.62}},
    'B2C Sales': {'aliases': ['b2c sales'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Inside Sales': 0.64}},
    'SaaS Sales': {'aliases': ['saas sales'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Enterprise Sales': 0.86, 'B2B Sales': 0.8, 'Inside Sales': 0.68}},
    'Enterprise Sales': {'aliases': ['enterprise sales'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'SaaS Sales': 0.88, 'B2B Sales': 0.8, 'Negotiation': 0.72}},
    'Inside Sales': {'aliases': ['inside sales'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Cold Calling': 0.72, 'B2B Sales': 0.62, 'Sales Executive': 0.64}},
    'Account Management': {'aliases': ['account management', 'account manager'], 'domain': 'sales_bd', 'family': 'sales/customer_management', 'related': {'Client Relationship Management': 0.86, 'Customer Success': 0.7, 'Renewals': 0.66}},
    'Negotiation': {'aliases': ['negotiation'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Deal Closure': 0.84}},
    'Pipeline Management': {'aliases': ['pipeline management'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Lead Generation': 0.64, 'CRM': 0.62, 'Revenue Growth': 0.56}},
    'Client Relationship Management': {'aliases': ['client relationship management', 'relationship management'], 'domain': 'sales_bd', 'family': 'sales/customer_management', 'related': {'CRM': 0.9, 'Account Management': 0.86, 'Customer Success': 0.76}},
    'Deal Closure': {'aliases': ['closing', 'deal closure', 'closing deals'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Negotiation': 0.84, 'Revenue Growth': 0.72}},
    'Revenue Growth': {'aliases': ['revenue growth'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Pipeline Management': 0.6, 'Deal Closure': 0.72}},
    'Sourcing': {'aliases': ['sourcing', 'candidate sourcing'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Talent Acquisition': 0.9, 'Recruitment': 0.82, 'LinkedIn Recruiter': 0.78, 'Boolean Search': 0.78}},
    'Talent Acquisition': {'aliases': ['talent acquisition'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Recruitment': 0.92, 'Sourcing': 0.88, 'Screening': 0.76}},
    'Recruitment': {'aliases': ['recruitment', 'recruiting'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Talent Acquisition': 0.92, 'Recruiter': 0.82, 'Sourcing': 0.82, 'Screening': 0.72}},
    'Boolean Search': {'aliases': ['boolean search'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Sourcing': 0.8, 'LinkedIn Recruiter': 0.66}},
    'Screening': {'aliases': ['screening', 'candidate screening'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Interview Coordination': 0.66, 'Talent Acquisition': 0.72}},
    'Interview Coordination': {'aliases': ['interview coordination', 'interview scheduling'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Screening': 0.64, 'Stakeholder Management': 0.62}},
    'Stakeholder Management': {'aliases': ['stakeholder management'], 'domain': 'product_project', 'family': 'cross_functional', 'related': {'Project Management': 0.72, 'Product Management': 0.72, 'Interview Coordination': 0.56, 'Program Management': 0.68}},
    'Offer Rollout': {'aliases': ['offer rollout', 'offer management'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Onboarding': 0.68}},
    'Onboarding': {'aliases': ['onboarding'], 'domain': 'recruiting_hr', 'family': 'recruiting/hr_operations', 'related': {'HR Operations': 0.72, 'Customer Success': 0.62, 'Renewals': 0.42}},
    'HR Operations': {'aliases': ['hr operations'], 'domain': 'recruiting_hr', 'family': 'recruiting/hr_operations', 'related': {'Payroll': 0.76, 'Employee Relations': 0.72, 'Onboarding': 0.7}},
    'Payroll': {'aliases': ['payroll'], 'domain': 'recruiting_hr', 'family': 'recruiting/hr_operations', 'related': {'HR Operations': 0.76}},
    'Employee Relations': {'aliases': ['employee relations'], 'domain': 'recruiting_hr', 'family': 'recruiting/hr_operations', 'related': {'Performance Management': 0.72, 'HR Operations': 0.72}},
    'Performance Management': {'aliases': ['performance management'], 'domain': 'recruiting_hr', 'family': 'recruiting/hr_operations', 'related': {'Employee Relations': 0.72}},
    'ATS': {'aliases': ['ats', 'applicant tracking system'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'LinkedIn Recruiter': 0.64}},
    'LinkedIn Recruiter': {'aliases': ['linkedin recruiter'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Sourcing': 0.8, 'ATS': 0.62}},
    'Customer Support': {'aliases': ['customer support'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Helpdesk': 0.82, 'Ticketing': 0.86, 'Issue Resolution': 0.84, 'Chat Support': 0.78, 'Email Support': 0.78}},
    'Customer Success': {'aliases': ['customer success'], 'domain': 'customer_success', 'family': 'customer/success', 'related': {'Retention': 0.82, 'Renewals': 0.84, 'Onboarding': 0.76, 'Account Management': 0.66, 'CRM': 0.6}},
    'Ticketing': {'aliases': ['ticketing', 'ticket management'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Helpdesk': 0.86, 'Escalation Management': 0.72, 'Issue Resolution': 0.74}},
    'Escalation Management': {'aliases': ['escalation management'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Issue Resolution': 0.82, 'Ticketing': 0.74}},
    'Retention': {'aliases': ['retention'], 'domain': 'customer_success', 'family': 'customer/success', 'related': {'Renewals': 0.84, 'Customer Success': 0.82}},
    'Renewals': {'aliases': ['renewals'], 'domain': 'customer_success', 'family': 'customer/success', 'related': {'Retention': 0.84, 'Customer Success': 0.84, 'Account Management': 0.66}},
    'Issue Resolution': {'aliases': ['issue resolution', 'problem solving'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Customer Support': 0.82, 'Escalation Management': 0.82}},
    'Helpdesk': {'aliases': ['helpdesk', 'help desk'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Ticketing': 0.86, 'Customer Support': 0.82}},
    'Chat Support': {'aliases': ['chat support'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Customer Support': 0.8}},
    'Email Support': {'aliases': ['email support'], 'domain': 'customer_success', 'family': 'customer/support', 'related': {'Customer Support': 0.8}},
    'Product Management': {'aliases': ['product management', 'product manager'], 'domain': 'product_project', 'family': 'product/management', 'related': {'Roadmapping': 0.86, 'PRD': 0.86, 'Backlog Management': 0.82, 'Agile': 0.72, 'Stakeholder Management': 0.72}},
    'Roadmapping': {'aliases': ['roadmapping', 'product roadmap'], 'domain': 'product_project', 'family': 'product/management', 'related': {'Product Management': 0.88, 'PRD': 0.76}},
    'PRD': {'aliases': ['prd', 'product requirement document', 'product requirements document'], 'domain': 'product_project', 'family': 'product/management', 'related': {'Product Management': 0.88, 'Roadmapping': 0.76, 'Backlog Management': 0.68}},
    'Backlog Management': {'aliases': ['backlog management', 'product backlog'], 'domain': 'product_project', 'family': 'product/management', 'related': {'Sprint Planning': 0.74, 'Agile': 0.7, 'Scrum': 0.7, 'Jira': 0.68}},
    'Sprint Planning': {'aliases': ['sprint planning'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Agile': 0.82, 'Scrum': 0.82, 'Backlog Management': 0.74}},
    'Agile': {'aliases': ['agile'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Scrum': 0.88, 'Sprint Planning': 0.82, 'Jira': 0.64, 'SDLC': 0.56}},
    'Scrum': {'aliases': ['scrum'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Agile': 0.88, 'Sprint Planning': 0.82}},
    'Jira': {'aliases': ['jira'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Agile': 0.66, 'Project Management': 0.62}},
    'Project Management': {'aliases': ['project management', 'project manager'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Program Management': 0.82, 'Delivery Management': 0.8, 'Stakeholder Management': 0.72}},
    'Program Management': {'aliases': ['program management', 'program manager'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Project Management': 0.82, 'Delivery Management': 0.78, 'Stakeholder Management': 0.68}},
    'Delivery Management': {'aliases': ['delivery management'], 'domain': 'product_project', 'family': 'project/delivery', 'related': {'Project Management': 0.8, 'Program Management': 0.78}},
    'Digital Marketing': {'aliases': ['digital marketing'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'SEO': 0.72, 'SEM': 0.72, 'Campaign Management': 0.78, 'Performance Marketing': 0.82}},
    'SEO': {'aliases': ['seo', 'search engine optimization'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'SEM': 0.72, 'Content Marketing': 0.72}},
    'SEM': {'aliases': ['sem', 'search engine marketing'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'Google Ads': 0.86, 'SEO': 0.72}},
    'Google Ads': {'aliases': ['google ads', 'adwords'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'SEM': 0.88, 'Performance Marketing': 0.82}},
    'Meta Ads': {'aliases': ['meta ads', 'facebook ads'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'Performance Marketing': 0.84, 'Campaign Management': 0.72}},
    'Campaign Management': {'aliases': ['campaign management'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'Digital Marketing': 0.78, 'Performance Marketing': 0.76, 'Email Marketing': 0.7}},
    'Content Marketing': {'aliases': ['content marketing'], 'domain': 'marketing_growth', 'family': 'marketing/content', 'related': {'Copywriting': 0.84, 'SEO': 0.72, 'Content Development': 0.72}},
    'Copywriting': {'aliases': ['copywriting', 'copy writer'], 'domain': 'marketing_growth', 'family': 'marketing/content', 'related': {'Content Marketing': 0.86, 'Social Media': 0.64}},
    'Email Marketing': {'aliases': ['email marketing'], 'domain': 'marketing_growth', 'family': 'marketing/lifecycle', 'related': {'Marketing Automation': 0.86, 'Lead Nurturing': 0.84, 'Campaign Management': 0.72}},
    'Marketing Automation': {'aliases': ['marketing automation'], 'domain': 'marketing_growth', 'family': 'marketing/lifecycle', 'related': {'Email Marketing': 0.88, 'HubSpot': 0.72, 'Lead Nurturing': 0.84}},
    'Lead Nurturing': {'aliases': ['lead nurturing'], 'domain': 'marketing_growth', 'family': 'marketing/lifecycle', 'related': {'Email Marketing': 0.84, 'Marketing Automation': 0.84}},
    'Brand Marketing': {'aliases': ['brand marketing'], 'domain': 'marketing_growth', 'family': 'marketing/brand', 'related': {'Campaign Management': 0.62, 'Social Media': 0.68}},
    'Performance Marketing': {'aliases': ['performance marketing'], 'domain': 'marketing_growth', 'family': 'marketing/performance', 'related': {'Google Ads': 0.84, 'Meta Ads': 0.84, 'Digital Marketing': 0.82}},
    'Social Media': {'aliases': ['social media', 'social media marketing'], 'domain': 'marketing_growth', 'family': 'marketing/content', 'related': {'Content Marketing': 0.68, 'Brand Marketing': 0.66}},
    'Accounting': {'aliases': ['accounting'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Bookkeeping': 0.86, 'Financial Reporting': 0.78, 'Reconciliation': 0.74, 'GST': 0.68, 'Tally': 0.66}},
    'Bookkeeping': {'aliases': ['bookkeeping'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Accounting': 0.88}},
    'Financial Reporting': {'aliases': ['financial reporting'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Accounting': 0.78, 'Budgeting': 0.72, 'Forecasting': 0.68}},
    'GST': {'aliases': ['gst'], 'domain': 'finance_accounting', 'family': 'finance/tax', 'related': {'Taxation': 0.88, 'Accounting': 0.68, 'Reconciliation': 0.56}},
    'Taxation': {'aliases': ['taxation', 'tax'], 'domain': 'finance_accounting', 'family': 'finance/tax', 'related': {'GST': 0.88, 'TDS': 0.82}},
    'TDS': {'aliases': ['tds'], 'domain': 'finance_accounting', 'family': 'finance/tax', 'related': {'Taxation': 0.84}},
    'Accounts Payable': {'aliases': ['accounts payable', 'ap'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Accounting': 0.74, 'Reconciliation': 0.62}},
    'Accounts Receivable': {'aliases': ['accounts receivable', 'ar'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Accounting': 0.74, 'Reconciliation': 0.62}},
    'Reconciliation': {'aliases': ['reconciliation', 'bank reconciliation'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Accounting': 0.78, 'Accounts Payable': 0.62, 'Accounts Receivable': 0.62, 'GST': 0.56}},
    'Audit': {'aliases': ['audit', 'auditing'], 'domain': 'finance_accounting', 'family': 'finance/audit', 'related': {'Compliance': 0.62, 'Financial Reporting': 0.72}},
    'Budgeting': {'aliases': ['budgeting'], 'domain': 'finance_accounting', 'family': 'finance/fp_and_a', 'related': {'Forecasting': 0.86, 'Financial Reporting': 0.68, 'Excel': 0.62}},
    'Forecasting': {'aliases': ['forecasting'], 'domain': 'finance_accounting', 'family': 'finance/fp_and_a', 'related': {'Budgeting': 0.86, 'Financial Reporting': 0.66}},
    'Excel': {'aliases': ['excel', 'ms excel', 'microsoft excel'], 'domain': 'finance_accounting', 'family': 'cross_functional', 'related': {'MIS Reporting': 0.68, 'Data Analysis': 0.72, 'Power BI': 0.68, 'Tally': 0.56}},
    'Tally': {'aliases': ['tally'], 'domain': 'finance_accounting', 'family': 'finance/accounting', 'related': {'Accounting': 0.68, 'Excel': 0.56}},
    'SAP Finance': {'aliases': ['sap finance', 'sap fico', 'fico'], 'domain': 'finance_accounting', 'family': 'finance/erp', 'related': {'Accounting': 0.62, 'Financial Reporting': 0.58}},
    'Vendor Management': {'aliases': ['vendor management'], 'domain': 'operations_admin', 'family': 'operations/procurement', 'related': {'Procurement': 0.86, 'Purchase Orders': 0.74}},
    'Procurement': {'aliases': ['procurement'], 'domain': 'operations_admin', 'family': 'operations/procurement', 'related': {'Vendor Management': 0.86, 'Purchase Orders': 0.84, 'Inventory Management': 0.68}},
    'Purchase Orders': {'aliases': ['purchase orders', 'purchase order', 'po processing'], 'domain': 'operations_admin', 'family': 'operations/procurement', 'related': {'Procurement': 0.86, 'Vendor Management': 0.72}},
    'Inventory Management': {'aliases': ['inventory management'], 'domain': 'operations_admin', 'family': 'operations/operations', 'related': {'Operations Management': 0.72, 'Procurement': 0.68, 'Supply Chain': 0.74}},
    'Operations Management': {'aliases': ['operations management'], 'domain': 'operations_admin', 'family': 'operations/operations', 'related': {'MIS Reporting': 0.64, 'Coordination': 0.62, 'Administrative Support': 0.56}},
    'MIS Reporting': {'aliases': ['mis reporting', 'mis'], 'domain': 'operations_admin', 'family': 'operations/reporting', 'related': {'Excel': 0.68, 'Operations Management': 0.62}},
    'Administrative Support': {'aliases': ['administrative support', 'admin support'], 'domain': 'operations_admin', 'family': 'operations/admin', 'related': {'Documentation': 0.72, 'Coordination': 0.72}},
    'Documentation': {'aliases': ['documentation'], 'domain': 'operations_admin', 'family': 'operations/admin', 'related': {'Administrative Support': 0.74, 'Compliance': 0.62, 'Contract Drafting': 0.56}},
    'Compliance': {'aliases': ['compliance'], 'domain': 'legal_compliance', 'family': 'legal/compliance', 'related': {'Regulatory': 0.84, 'Risk': 0.72, 'Audit': 0.62, 'Documentation': 0.58}},
    'Coordination': {'aliases': ['coordination'], 'domain': 'operations_admin', 'family': 'operations/admin', 'related': {'Administrative Support': 0.74, 'Operations Management': 0.62}},
    'Supply Chain': {'aliases': ['supply chain'], 'domain': 'operations_admin', 'family': 'operations/procurement', 'related': {'Procurement': 0.76, 'Inventory Management': 0.74}},
    'UI Design': {'aliases': ['ui design', 'user interface design'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'UX Design': 0.76, 'Visual Design': 0.82, 'Figma': 0.78}},
    'UX Design': {'aliases': ['ux design', 'user experience design'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'UI Design': 0.76, 'Wireframing': 0.82, 'User Research': 0.82, 'Interaction Design': 0.8}},
    'Wireframing': {'aliases': ['wireframing', 'wireframes'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'Prototyping': 0.86, 'UX Design': 0.8}},
    'Prototyping': {'aliases': ['prototyping', 'prototype'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'Wireframing': 0.86, 'Figma': 0.78, 'Adobe XD': 0.74}},
    'Figma': {'aliases': ['figma'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'Prototyping': 0.78, 'UI Design': 0.78}},
    'Adobe XD': {'aliases': ['adobe xd', 'xd'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'Prototyping': 0.76}},
    'User Research': {'aliases': ['user research'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'UX Design': 0.84, 'Interaction Design': 0.72}},
    'Interaction Design': {'aliases': ['interaction design'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'UX Design': 0.82, 'Visual Design': 0.62}},
    'Visual Design': {'aliases': ['visual design'], 'domain': 'design_ux_ui', 'family': 'design/ui_ux', 'related': {'UI Design': 0.84, 'Interaction Design': 0.62}},
    'Contract Drafting': {'aliases': ['contract drafting'], 'domain': 'legal_compliance', 'family': 'legal/contracts', 'related': {'Legal Research': 0.72, 'Corporate Law': 0.68, 'Documentation': 0.56}},
    'Legal Research': {'aliases': ['legal research'], 'domain': 'legal_compliance', 'family': 'legal/general', 'related': {'Contract Drafting': 0.72, 'Corporate Law': 0.66, 'Labour Law': 0.66}},
    'Regulatory': {'aliases': ['regulatory', 'regulatory compliance'], 'domain': 'legal_compliance', 'family': 'legal/compliance', 'related': {'Compliance': 0.86, 'Risk': 0.7}},
    'Risk': {'aliases': ['risk', 'risk management'], 'domain': 'legal_compliance', 'family': 'legal/compliance', 'related': {'Compliance': 0.72, 'Regulatory': 0.7}},
    'Policy': {'aliases': ['policy', 'policy drafting'], 'domain': 'legal_compliance', 'family': 'legal/compliance', 'related': {'Compliance': 0.68}},
    'Corporate Law': {'aliases': ['corporate law'], 'domain': 'legal_compliance', 'family': 'legal/general', 'related': {'Contract Drafting': 0.68, 'Legal Research': 0.66}},
    'Labour Law': {'aliases': ['labour law', 'labor law'], 'domain': 'legal_compliance', 'family': 'legal/general', 'related': {'Legal Research': 0.66, 'Employee Relations': 0.62}},
    'Clinical Research': {'aliases': ['clinical research'], 'domain': 'healthcare', 'family': 'healthcare/clinical', 'related': {'Pharmacovigilance': 0.74, 'Healthcare Operations': 0.58}},
    'Patient Care': {'aliases': ['patient care'], 'domain': 'healthcare', 'family': 'healthcare/clinical', 'related': {'Healthcare Operations': 0.56}},
    'Medical Coding': {'aliases': ['medical coding'], 'domain': 'healthcare', 'family': 'healthcare/operations', 'related': {'Medical Billing': 0.84}},
    'Medical Billing': {'aliases': ['medical billing'], 'domain': 'healthcare', 'family': 'healthcare/operations', 'related': {'Medical Coding': 0.84}},
    'Pharmacovigilance': {'aliases': ['pharmacovigilance'], 'domain': 'healthcare', 'family': 'healthcare/clinical', 'related': {'Clinical Research': 0.74}},
    'Healthcare Operations': {'aliases': ['healthcare operations'], 'domain': 'healthcare', 'family': 'healthcare/operations', 'related': {'Hospital Administration': 0.78, 'EMR/EHR': 0.62}},
    'EMR/EHR': {'aliases': ['emr', 'ehr', 'emr/ehr'], 'domain': 'healthcare', 'family': 'healthcare/operations', 'related': {'Healthcare Operations': 0.62, 'Hospital Administration': 0.56}},
    'Hospital Administration': {'aliases': ['hospital administration'], 'domain': 'healthcare', 'family': 'healthcare/operations', 'related': {'Healthcare Operations': 0.78}},
    'Teaching': {'aliases': ['teaching'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Curriculum Development': 0.76, 'Training Delivery': 0.74, 'Assessment Design': 0.62}},
    'Curriculum Development': {'aliases': ['curriculum development'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Teaching': 0.78, 'Instructional Design': 0.82, 'Content Development': 0.7}},
    'Training Delivery': {'aliases': ['training delivery'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Teaching': 0.74, 'Instructional Design': 0.66}},
    'Instructional Design': {'aliases': ['instructional design'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Curriculum Development': 0.84, 'LMS': 0.66, 'Assessment Design': 0.72}},
    'Assessment Design': {'aliases': ['assessment design'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Teaching': 0.62, 'Instructional Design': 0.72}},
    'LMS': {'aliases': ['lms', 'learning management system'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Instructional Design': 0.66, 'Training Delivery': 0.54}},
    'Content Development': {'aliases': ['content development'], 'domain': 'education_ld', 'family': 'education/training', 'related': {'Curriculum Development': 0.72, 'Content Marketing': 0.66}},
    'Apex': {'aliases': ['apex'], 'domain': 'engineering', 'family': 'engineering/crm_platform', 'related': {'Salesforce': 0.9, 'Lightning': 0.82, 'SOQL': 0.78, 'Visualforce': 0.74}},
    'Lightning': {'aliases': ['lightning', 'lightning web components', 'lwc'], 'domain': 'engineering', 'family': 'engineering/crm_platform', 'related': {'Salesforce': 0.9, 'Apex': 0.82, 'Visualforce': 0.66}},
    'SOQL': {'aliases': ['soql'], 'domain': 'engineering', 'family': 'engineering/crm_platform', 'related': {'Salesforce': 0.82, 'Apex': 0.72}},
    'Visualforce': {'aliases': ['visualforce'], 'domain': 'engineering', 'family': 'engineering/crm_platform', 'related': {'Salesforce': 0.78, 'Apex': 0.72}},
    'Recruiter': {'aliases': ['recruiter', 'hr recruiter'], 'domain': 'recruiting_hr', 'family': 'recruiting/talent_acquisition', 'related': {'Recruitment': 0.82, 'Talent Acquisition': 0.84}},
    'Sales Executive': {'aliases': ['sales executive'], 'domain': 'sales_bd', 'family': 'sales/business_development', 'related': {'Inside Sales': 0.7, 'B2B Sales': 0.62}},
}


ROLE_FAMILY_KEYWORDS: dict[str, dict[str, object]] = {
    'engineering': {
        'subfamily': 'software',
        'title_aliases': ['software engineer', 'software developer', 'developer', 'engineer'],
        'skill_hints': ['Python', 'Java', 'JavaScript', 'Node.js', 'React', 'Angular', 'REST API'],
    },
    'engineering_fullstack': {
        'family': 'engineering',
        'subfamily': 'fullstack',
        'title_aliases': ['python fullstack', 'full stack developer', 'fullstack developer', 'full stack engineer', 'fullstack engineer'],
        'skill_hints': ['Python', 'JavaScript', 'React', 'Node.js', 'Django', 'REST API'],
    },
    'engineering_backend': {
        'family': 'engineering',
        'subfamily': 'backend',
        'title_aliases': ['backend developer', 'backend engineer', 'python developer', 'api developer'],
        'skill_hints': ['Python', 'Java', 'Flask', 'FastAPI', 'Django', 'REST API'],
    },
    'engineering_frontend': {
        'family': 'engineering',
        'subfamily': 'frontend',
        'title_aliases': ['frontend developer', 'frontend engineer', 'ui developer'],
        'skill_hints': ['JavaScript', 'TypeScript', 'React', 'Angular', 'Vue', 'HTML', 'CSS'],
    },
    'engineering_crm_platform': {
        'family': 'engineering',
        'subfamily': 'crm_platform',
        'title_aliases': ['salesforce developer', 'salesforce engineer', 'crm developer'],
        'skill_hints': ['Salesforce', 'Apex', 'Lightning', 'SOQL', 'Visualforce'],
    },
    'data_ai_ml': {
        'family': 'data_ai_ml',
        'subfamily': 'ml',
        'title_aliases': ['data scientist', 'ml engineer', 'machine learning engineer', 'ai engineer'],
        'skill_hints': ['Machine Learning', 'Deep Learning', 'TensorFlow', 'PyTorch', 'Python', 'NLP', 'LLM'],
    },
    'data_analytics': {
        'family': 'analytics_bi',
        'subfamily': 'business_intelligence',
        'title_aliases': ['data analyst', 'business analyst', 'bi analyst', 'business intelligence analyst'],
        'skill_hints': ['SQL', 'Excel', 'Power BI', 'Tableau', 'Data Analysis'],
    },
    'qa_testing': {
        'family': 'qa_testing',
        'subfamily': 'testing',
        'title_aliases': ['qa engineer', 'test engineer', 'automation tester', 'qa analyst'],
        'skill_hints': ['QA', 'Manual Testing', 'Automation Testing', 'Selenium', 'Cypress', 'Playwright'],
    },
    'devops_cloud': {
        'family': 'devops_cloud',
        'subfamily': 'cloud',
        'title_aliases': ['devops engineer', 'site reliability engineer', 'cloud engineer', 'platform engineer'],
        'skill_hints': ['AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'Linux'],
    },
    'product_management': {
        'family': 'product_project',
        'subfamily': 'product_management',
        'title_aliases': ['product manager', 'associate product manager'],
        'skill_hints': ['Product Management', 'Roadmapping', 'PRD', 'Backlog Management', 'Agile'],
    },
    'project_management': {
        'family': 'product_project',
        'subfamily': 'project_management',
        'title_aliases': ['project manager', 'program manager', 'delivery manager'],
        'skill_hints': ['Project Management', 'Program Management', 'Delivery Management', 'Stakeholder Management', 'Jira'],
    },
    'design': {
        'family': 'design_ux_ui',
        'subfamily': 'ui_ux',
        'title_aliases': ['ui designer', 'ux designer', 'product designer', 'visual designer'],
        'skill_hints': ['UI Design', 'UX Design', 'Wireframing', 'Prototyping', 'Figma'],
    },
    'sales': {
        'family': 'sales_bd',
        'subfamily': 'business_development',
        'title_aliases': ['sales executive', 'business development executive', 'inside sales executive', 'account executive'],
        'skill_hints': ['Lead Generation', 'Prospecting', 'Cold Calling', 'CRM', 'B2B Sales', 'SaaS Sales'],
    },
    'customer_success': {
        'family': 'customer_success',
        'subfamily': 'success',
        'title_aliases': ['customer success manager', 'customer success executive', 'account manager'],
        'skill_hints': ['Customer Success', 'Retention', 'Renewals', 'Onboarding', 'CRM'],
    },
    'customer_support': {
        'family': 'customer_success',
        'subfamily': 'support',
        'title_aliases': ['customer support executive', 'support associate', 'support lead'],
        'skill_hints': ['Customer Support', 'Ticketing', 'Helpdesk', 'Escalation Management', 'Issue Resolution'],
    },
    'recruiting': {
        'family': 'recruiting_hr',
        'subfamily': 'talent_acquisition',
        'title_aliases': ['recruiter', 'hr recruiter', 'talent acquisition specialist', 'sourcing specialist'],
        'skill_hints': ['Recruitment', 'Talent Acquisition', 'Sourcing', 'Boolean Search', 'Screening'],
    },
    'hr_operations': {
        'family': 'recruiting_hr',
        'subfamily': 'hr_operations',
        'title_aliases': ['hr executive', 'hr operations specialist'],
        'skill_hints': ['HR Operations', 'Payroll', 'Employee Relations', 'Onboarding'],
    },
    'finance_accounting': {
        'family': 'finance_accounting',
        'subfamily': 'accounting',
        'title_aliases': ['accountant', 'senior accountant', 'finance executive', 'accounts executive', 'audit associate'],
        'skill_hints': ['Accounting', 'GST', 'Reconciliation', 'Financial Reporting', 'Tally', 'Excel'],
    },
    'operations_procurement': {
        'family': 'operations_admin',
        'subfamily': 'procurement',
        'title_aliases': ['procurement executive', 'operations executive', 'purchase executive', 'admin executive'],
        'skill_hints': ['Procurement', 'Vendor Management', 'Purchase Orders', 'Inventory Management', 'Operations Management'],
    },
    'marketing_growth': {
        'family': 'marketing_growth',
        'subfamily': 'performance',
        'title_aliases': ['digital marketing specialist', 'growth marketer', 'seo specialist', 'performance marketer', 'content marketer'],
        'skill_hints': ['Digital Marketing', 'SEO', 'SEM', 'Google Ads', 'Meta Ads', 'Content Marketing', 'Email Marketing'],
    },
    'legal_compliance': {
        'family': 'legal_compliance',
        'subfamily': 'compliance',
        'title_aliases': ['legal associate', 'compliance officer', 'legal executive'],
        'skill_hints': ['Compliance', 'Contract Drafting', 'Legal Research', 'Regulatory', 'Risk'],
    },
    'healthcare': {
        'family': 'healthcare',
        'subfamily': 'clinical_ops',
        'title_aliases': ['clinical research coordinator', 'medical coder', 'hospital administrator'],
        'skill_hints': ['Clinical Research', 'Medical Coding', 'Medical Billing', 'Healthcare Operations', 'EMR/EHR'],
    },
    'education': {
        'family': 'education_ld',
        'subfamily': 'training',
        'title_aliases': ['trainer', 'learning and development specialist', 'instructional designer', 'teacher'],
        'skill_hints': ['Teaching', 'Curriculum Development', 'Training Delivery', 'Instructional Design', 'LMS'],
    },
}


TITLE_ADJACENCY: dict[str, dict[str, float]] = {
    'Python Fullstack': {
        'Python Developer': 0.9,
        'Full Stack Developer': 0.85,
        'Django Developer': 0.9,
        'Backend Developer': 0.65,
        'Software Engineer': 0.45,
    },
    'Sales Executive': {
        'Business Development Executive': 0.9,
        'Inside Sales Executive': 0.9,
        'Sales Associate': 0.75,
        'Account Executive': 0.8,
    },
    'Recruiter': {
        'Talent Acquisition Specialist': 0.95,
        'HR Recruiter': 0.9,
        'Sourcing Specialist': 0.75,
    },
    'Customer Success Manager': {
        'Customer Success Executive': 0.85,
        'Account Manager': 0.65,
        'Support Lead': 0.45,
    },
    'Product Manager': {
        'Associate Product Manager': 0.85,
        'Program Manager': 0.55,
        'Business Analyst': 0.45,
    },
    'Salesforce Developer': {
        'Salesforce Engineer': 0.95,
        'CRM Developer': 0.82,
        'Software Engineer': 0.32,
    },
    'Customer Support Executive': {
        'Support Associate': 0.8,
        'Support Lead': 0.62,
        'Customer Success Executive': 0.42,
    },
    'Accountant': {
        'Senior Accountant': 0.88,
        'Finance Executive': 0.78,
        'Accounts Executive': 0.82,
        'Audit Associate': 0.62,
    },
}

