from django.urls import path

from smartInterviewApp.api.views import (
    AptitudeAssignmentCreateApi,
    AptitudeAssignmentDetailApi,
    AptitudeAssignmentResultApi,
    AptitudeDefaultReadinessApi,
    AptitudeRuntimeAnswerApi,
    AptitudeRuntimeIntegrityEventApi,
    AptitudeRuntimeQuestionsApi,
    AptitudeRuntimeStartApi,
    AptitudeRuntimeStatusApi,
    AptitudeRuntimeSubmitApi,
    AptitudeTemplateReadinessApi,
    ExotelWebhookApi,
    MetaWhatsappWebhookApi,
    Msg91WebhookApi,
    NotificationDetailApi,
    RequestOtpApi,
    ResendOtpApi,
    SendNotificationApi,
    VerifyOtpApi,
)

urlpatterns = [
    path('auth/request-otp/', RequestOtpApi.as_view(), name='api-request-otp'),
    path('auth/verify-otp/', VerifyOtpApi.as_view(), name='api-verify-otp'),
    path('auth/resend-otp/', ResendOtpApi.as_view(), name='api-resend-otp'),
    path('aptitude/templates/<int:template_id>/readiness/', AptitudeTemplateReadinessApi.as_view(), name='api-aptitude-template-readiness'),
    path('aptitude/default-readiness/', AptitudeDefaultReadinessApi.as_view(), name='api-aptitude-default-readiness'),
    path('aptitude/assignments/create/', AptitudeAssignmentCreateApi.as_view(), name='api-aptitude-assignment-create'),
    path('aptitude/assignments/<int:assignment_id>/', AptitudeAssignmentDetailApi.as_view(), name='api-aptitude-assignment-detail'),
    path('aptitude/assignments/<int:assignment_id>/result/', AptitudeAssignmentResultApi.as_view(), name='api-aptitude-assignment-result'),
    path('aptitude/runtime/<str:public_token>/status/', AptitudeRuntimeStatusApi.as_view(), name='api-aptitude-runtime-status'),
    path('aptitude/runtime/<str:public_token>/start/', AptitudeRuntimeStartApi.as_view(), name='api-aptitude-runtime-start'),
    path('aptitude/runtime/<str:public_token>/questions/', AptitudeRuntimeQuestionsApi.as_view(), name='api-aptitude-runtime-questions'),
    path('aptitude/runtime/<str:public_token>/answer/', AptitudeRuntimeAnswerApi.as_view(), name='api-aptitude-runtime-answer'),
    path('aptitude/runtime/<str:public_token>/submit/', AptitudeRuntimeSubmitApi.as_view(), name='api-aptitude-runtime-submit'),
    path('aptitude/runtime/<str:public_token>/integrity-event/', AptitudeRuntimeIntegrityEventApi.as_view(), name='api-aptitude-runtime-integrity-event'),
    path('notifications/send/', SendNotificationApi.as_view(), name='api-notifications-send'),
    path('notifications/<int:notification_id>/', NotificationDetailApi.as_view(), name='api-notifications-detail'),
    path('webhooks/whatsapp/meta/', MetaWhatsappWebhookApi.as_view(), name='api-webhook-meta-whatsapp'),
    path('webhooks/msg91/', Msg91WebhookApi.as_view(), name='api-webhook-msg91'),
    path('webhooks/exotel/', ExotelWebhookApi.as_view(), name='api-webhook-exotel'),
]
