# Generated by Django 5.2.5 on 2025-09-22 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='recruiter',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'recruiter'}, related_name='vacancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
