# Generated by Django 4.2.7 on 2026-03-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0019_companyprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyprofile',
            new_name='smartInterv_industr_51cc76_idx',
            old_name='smartInterv_industr_85fdb8_idx',
        ),
        migrations.RenameIndex(
            model_name='companyprofile',
            new_name='smartInterv_company_f64c9d_idx',
            old_name='smartInterv_company_aac1ac_idx',
        ),
        migrations.RenameIndex(
            model_name='companyprofile',
            new_name='smartInterv_legal_n_2ffadd_idx',
            old_name='smartInterv_legal_n_7869b0_idx',
        ),
    ]
