# Generated by Django 4.2.7 on 2026-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0027_candidate_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('assessment_pending', 'Assessment Pending'), ('rejected', 'Rejected'), ('assessment_completed', 'Assessment Completed'), ('auto_screening_scheduled', 'Auto Screening Scheduled')], default='scheduled', max_length=50),
        ),
    ]
