# Generated by Django 4.2.7 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0045_resume_ai_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='profile_strength_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='profile_strength_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='profile_strength_missing_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='profile_strength_confidence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='role_fit_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='role_fit_confidence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='role_fit_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='role_fit_matched_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='role_fit_missing_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateinsightsnapshot',
            name='data_quality_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
