# Generated by Django 4.2.7 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0046_candidate_insight_trust_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateidentityverification',
            name='live_selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity/live_selfies/'),
        ),
        migrations.AddField(
            model_name='candidateidentityverification',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateidentityverification',
            name='face_match_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateidentityverification',
            name='face_match_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidateidentityverification',
            name='status',
            field=models.CharField(choices=[
                ('not_started', 'Not Started'),
                ('processing', 'Processing'),
                ('xml_verified', 'XML Verified'),
                ('document_matched', 'Document Matched'),
                ('document_mismatch', 'Document Mismatch'),
                ('selfie_captured', 'Selfie Captured'),
                ('face_matched', 'Face Matched'),
                ('face_mismatch', 'Face Mismatch'),
                ('profile_photo_required', 'Profile Photo Required'),
                ('failed', 'Failed'),
            ], default='not_started', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidateidentityverification',
            name='verification_method',
            field=models.CharField(blank=True, choices=[
                ('offline_xml', 'Offline XML'),
                ('document_upload', 'Document Upload'),
                ('live_selfie', 'Live Selfie'),
            ], default='', max_length=30),
        ),
    ]
