# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartInterviewApp', '0047_live_selfie_identity_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcallsession',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='interviewcallsession',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewcallsession',
            name='note_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
